/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student;

/**
 *
 * @author Tasnim Ahmed
 */
public class TeacherMenu extends javax.swing.JPanel {

    /**
     * Creates new form TeacherMenu
     */
    public TeacherMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jTextField4 = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1210, 670));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(29, 32, 38));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(29, 32, 38));
        jTextField1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(null);
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 230, 50));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 230, 20));

        jLabel19.setBackground(new java.awt.Color(29, 32, 38));
        jLabel19.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("username");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 110, 30));

        jPasswordField1.setBackground(new java.awt.Color(29, 32, 38));
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField1.setBorder(null);
        jPanel2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 230, 50));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 230, 20));

        jLabel20.setBackground(new java.awt.Color(29, 32, 38));
        jLabel20.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("password");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 110, 20));

        jButton1.setBackground(new java.awt.Color(29, 32, 38));
        jButton1.setForeground(java.awt.Color.white);
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/signup.png"))); // NOI18N
        jButton1.setToolTipText("Create Account");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 70, 80));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 670));

        jLabel18.setFont(new java.awt.Font("Zapfino", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Name ");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 60, 50));

        jSeparator15.setBackground(new java.awt.Color(29, 32, 38));
        add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 630, 370, 30));

        jSeparator13.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 370, 30));

        jLabel14.setFont(new java.awt.Font("Zapfino", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Address");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, 120, 50));

        jTextField7.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(29, 32, 38));
        jTextField7.setBorder(null);
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, 350, 40));

        jTextField6.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(29, 32, 38));
        jTextField6.setBorder(null);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 580, 350, 40));

        jSeparator9.setBackground(new java.awt.Color(29, 32, 38));
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, 370, 30));

        jTextField4.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(29, 32, 38));
        jTextField4.setBorder(null);
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 350, 40));

        jSeparator14.setBackground(new java.awt.Color(29, 32, 38));
        add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 370, 30));

        jLabel2.setFont(new java.awt.Font("Zapfino", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Sex");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 60, 50));

        jSeparator10.setBackground(new java.awt.Color(29, 32, 38));
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 380, 370, 30));

        jLabel10.setFont(new java.awt.Font("Zapfino", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Department");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 280, 190, 50));

        jLabel16.setFont(new java.awt.Font("Zapfino", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Contact");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 410, 180, 50));

        jLabel4.setFont(new java.awt.Font("Zapfino", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Age");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 60, 50));

        jLabel8.setFont(new java.awt.Font("Zapfino", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("DOB");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, 130, 50));

        jSeparator6.setBackground(new java.awt.Color(29, 32, 38));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 500, 370, 30));

        jSeparator8.setBackground(new java.awt.Color(29, 32, 38));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 370, 30));

        jTextField3.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(29, 32, 38));
        jTextField3.setBorder(null);
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 350, 40));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jButton2.setToolTipText("Back To Database");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setPreferredSize(new java.awt.Dimension(70, 70));
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STUDENT INFORMATION SYSTEM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 610, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 960, 170));

        jTextField2.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(29, 32, 38));
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 450, 350, 40));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 370, 40));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EEE", "CSE", "MCE", "CEE" }));
        add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 340, 370, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JComboBox<String> jComboBox2;
    public javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    public javax.swing.JTextField jTextField4;
    public javax.swing.JTextField jTextField6;
    public javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
